name: Test github actions for Plugin Modernizer
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-modernizer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Plugin Modernizer Action
        uses: ./.github/actions/modernizer-action
        with:
          command: 'validate'
          arguments: '--debug'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
